{
 "title": "filtered adhoc queries",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "adhoc" },
   { "name": "adhoc_influx" }
  ]
 },
 "panels": [
  {
   "title": "influx cpu usage_idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "go_gc_pauses_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_gc_pauses_seconds_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "grafana_sse_ds_queries_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "grafana_sse_ds_queries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}